# Generated by Django 4.1.5 on 2023-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('dmodel', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('last_pm', models.DateField()),
                ('next_pm', models.DateField()),
                ('install_date', models.DateField()),
                ('history', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
